---
dashboard:
  stepToFirstStateAutomatically: true
  messageSpeed: 400 # Word per minute
  layout: web-only
  enabledLayouts:
    #- terminal-ide-web
    #- terminal-ide-vertical
    #- terminal-web
    #- ide-web-vertical
    - terminal-ide-horizontal
    #- terminal-only
    #- ide-only
    - web-only
webservice:
  iframeUrl: /webservice
  showUrlBar: false
  reloadIframeOnDeploy: false
terminal:
  directory: /home/user
  terminalMenuItem: terminal # terminal / console
ide:
  patterns: 
   - /home/user/tutorial/*
  showDeployButton: true
  deployButtonText:
    TODEPLOY:  Deploy
    DEPLOYED:  Deployed
    DEPLOYING: Reloading app...
    FAILED:    Deployment failed

#### States and messages ####
states:
 -
  ide.showDeployButton: true
  messages:
    - "Welcome to the next gen TFW demo. Do you like it so far?"
  buttons:
    - 'yes'

 -
  dashboard.layout: terminal-ide-horizontal
  terminal.write: "echo 'hello'"
  messages:
   - "You can send multiline message easily even from a config file.

   See?"


##### CHEAT SHEET OF ADDITIONAL COMMANDS #####
# ide.selectFile: /path/filename    - Selects the file in webIDE (make sure it's in the pattern!)
# webservice.reloadIframe: True     - Reloads the iframe immediately
# terminal.write: echo 'hello'      - Writes command to terminal
# console.write: Welcome user       - Writes text to console
  